################################################################
# Router configuration
################################################################

[http]
  [http.routers]
    [http.routers.http-to-web-app]
      rule = "Host(`example.com`) || (Host(`example.test`) && Path(`/app1`))"
      service = "web-app"
      entrypoints = ["web"]

################################################################
# Service configuration
################################################################

  [http.services]
    [http.services.web-app]
      [http.services.web-app.loadBalancer]
        passHostHeader = true
        [[http.services.web-app.loadBalancer.servers]]

